AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: java8
    MemorySize: 1536
    Timeout: 28
        
    Tags:
      service: insolabs_meetup_serverless
          
Resources:

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: insolabs-meetup-queue
      DelaySeconds: 0
      VisibilityTimeout: 120      
      MessageRetentionPeriod: 900
      
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "insolabs_topic"
      DisplayName: "Hello Insolentes"

########   #######  ##       ####  ######  ##    ## 
##     ## ##     ## ##        ##  ##    ##  ##  ##  
##     ## ##     ## ##        ##  ##         ####   
########  ##     ## ##        ##  ##          ##    
##        ##     ## ##        ##  ##          ##    
##        ##     ## ##        ##  ##    ##    ##    
##         #######  ######## ####  ######     ##

  PublishTopicPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: !Ref Topic
            
  SaveClientTopicPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Action:
              - sns:Subscribe
            Resource: !Ref Topic
  
  QueueListenerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt Queue.Arn
                        
##          ###    ##     ## ########  ########     ###    
##         ## ##   ###   ### ##     ## ##     ##   ## ##   
##        ##   ##  #### #### ##     ## ##     ##  ##   ##  
##       ##     ## ## ### ## ########  ##     ## ##     ## 
##       ######### ##     ## ##     ## ##     ## ######### 
##       ##     ## ##     ## ##     ## ##     ## ##     ## 
######## ##     ## ##     ## ########  ########  ##     ##
  
  LambdaApiSaveCellphone:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/distributions/app-0.1-SNAPSHOT.zip
      FunctionName: insolabs-serverless-api-SaveCellphone
      Handler: com.br.insolabs.serverless.handler.api.SaveCellphone::handleRequest
      Environment:
        Variables:
          topicArn: !Ref Topic
      Policies:
        - !Ref SaveClientTopicPolicy
        
  LambdaQueueListener:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      CodeUri: build/distributions/app-0.1-SNAPSHOT.zip
      FunctionName: insolabs-serverless-queue-Listener
      Handler: com.br.insolabs.serverless.handler.queue.Listener::handleRequest
      Environment:
        Variables:
          topicArn: !Ref Topic
      Policies:
        - !Ref QueueListenerPolicy
        - !Ref PublishTopicPolicy
        
########  ######## ########  ##     ## ####  ######   ######  ####  #######  ##    ## 
##     ## ##       ##     ## ###   ###  ##  ##    ## ##    ##  ##  ##     ## ###   ## 
##     ## ##       ##     ## #### ####  ##  ##       ##        ##  ##     ## ####  ## 
########  ######   ########  ## ### ##  ##   ######   ######   ##  ##     ## ## ## ## 
##        ##       ##   ##   ##     ##  ##        ##       ##  ##  ##     ## ##  #### 
##        ##       ##    ##  ##     ##  ##  ##    ## ##    ##  ##  ##     ## ##   ### 
##        ######## ##     ## ##     ## ####  ######   ######  ####  #######  ##    ## 

  FunctionSqsSendMessageEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !GetAtt Queue.Arn
      FunctionName: !GetAtt LambdaQueueListener.Arn
      
      
   ###    ########  ####           ######      ###    ######## ######## ##      ##    ###    ##    ## 
  ## ##   ##     ##  ##           ##    ##    ## ##      ##    ##       ##  ##  ##   ## ##    ##  ##  
 ##   ##  ##     ##  ##           ##         ##   ##     ##    ##       ##  ##  ##  ##   ##    ####   
##     ## ########   ##           ##   #### ##     ##    ##    ######   ##  ##  ## ##     ##    ##    
######### ##         ##           ##    ##  #########    ##    ##       ##  ##  ## #########    ##    
##     ## ##         ##           ##    ##  ##     ##    ##    ##       ##  ##  ## ##     ##    ##    
##     ## ##        ####           ######   ##     ##    ##    ########  ###  ###  ##     ##    ##    
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: insolabs-meetup-serverless
      EndpointConfiguration:
        Types:
          - 'REGIONAL'
      Policy: 
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": "*",
                "Action": "execute-api:Invoke",
                "Resource": "arn:aws:execute-api:us-east-1:*:*/*"
              }
            ]
          }
          
  # Role (assume role)
  APIGatewayInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
              
  # Policy
  APIGatewayInvokePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: APIGatewayInvokePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - lambda:InvokeFunction
            Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:insolabs-serverless-api-*"
      Roles:
        - !Ref APIGatewayInvokeRole

  # Path /cellphone
  ApiGatewayResourceCellphone:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: "cellphone"
      RestApiId: !Ref ApiGateway

  # POST /cellphone
  ApiGatewayMethodSaveCellphone:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        Credentials: !GetAtt APIGatewayInvokeRole.Arn
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaApiSaveCellphone.Arn}/invocations
      HttpMethod: POST
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayResourceCellphone
      MethodResponses:
        - StatusCode: 200
        
  #Deploy
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayMethodSaveCellphone
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: 'deploy'